RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

OLED_ENABLE = yes

VIA_ENABLE = yes

COMBO_ENABLE = yes

TAP_DANCE_ENABLE = yes

EXTRAKEY_ENABLE = yes

# 容量削減のための設定
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no